fastlane_version '2.102.0'

desc 'Various checks for git branch'
lane :git_check do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   
   # iOS Lanes 🍏

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'io.sevenlabs.app', type: 'development', readonly: true)
    match(app_identifier: 'io.sevenlabs.app', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  lane :build do
    gym(
      scheme: 'App', 
      workspace: "./ios/App/App.xcworkspace", 
      include_bitcode: false
    )
  end

  desc 'Increment the build bersion.'
  lane :bump do
    increment_build_number(
      build_number: latest_testflight_build_number(
        app_identifier: 'io.sevenlabs.app',
        username: 'marco@sevenlabs.io',
        team_name: 'Seven Labs Limited',
        team_id: '122448679',
      ) + 1,
      xcodeproj: "./ios/App/App.xcodeproj"
    )
  end
  
  desc 'Ship to Testflight.'
  lane :beta do
    git_check
    certificates
    build
    changes = changelog_from_git_commits
    pilot(
      app_identifier: 'io.sevenlabs.app',
      username: 'marco@sevenlabs.io',
      team_id: '122448679',
      team_name: 'Seven Labs Limited',
      changelog: changes
    )
  end

  desc 'Ship to TestFlight in CI'
  lane :beta_ci do
    bump
    create_keychain(
      name: "Fastlane_CI",
      password: "CI_Password",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(type: "development", readonly: true, keychain_name: 'Fastlane_CI', keychain_password: 'CI_Password')
    match(type: "appstore", readonly: true, keychain_name: 'Fastlane_CI', keychain_password: 'CI_Password')
    build
    changes
    pilot(
      app_identifier: 'io.sevenlabs.app',
      username: 'marco@sevenlabs.io',
      team_id: '122448679',
      team_name: 'Seven Labs Limited',
      changelog: changes,
      skip_waiting_for_build_processing: true,
    )
  end 

end

platform :android do
  # Android Lanes 🤖
  desc 'Build the Android application for Debug.'
  lane :apk do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'app:assemble', build_type: 'Debug', project_dir: 'android/')
  end

  desc 'Build the Android application for Release.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'app:assemble', build_type: 'Release', project_dir: 'android/')
  end
  
  desc 'Ship to Playstore Beta.'
  lane :beta do
    git_check
    build
    gradle(task: 'incrementVersionCode', project_dir: 'android/')
    supply(track: 'beta', track_promote_to: 'beta')
  end
end
