name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    name: Lint & Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Install and Run TDEX Daemon
        shell: 'script -q -e -c "bash {0}"'
        run: yarn tdex:run-init

      - name: Run electrs-batch-server
        shell: bash
        run: |
          git clone https://github.com/vulpemventures/electrs-batch-server.git
          cd electrs-batch-server
          export ELECTRS_URL=http://localhost:3001
          export PORT=5500
          export CONCURRENCY=10
          npm install
          npm start &
          cd ..

      - run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Test
        run: yarn test --ci --maxWorkers=2

      - name: Build
        run: CI="" yarn build
