name: Main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # The type of runner that the job will run on
    name: Lint & Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Nigiri
        run: |
          mkdir -p tmp; cd tmp
          curl https://travis.nigiri.network | bash; cd ..
          docker-compose -f  tmp/docker-compose.yml up -d

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test --ci --maxWorkers=2
