name: Main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # The type of runner that the job will run on
    name: Lint & Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Install and Run TDEX Daemon
        shell: 'script -q -e -c "bash {0}"'
        run: yarn tdex:run

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run serve:no-open
          wait-on: 'http://localhost:8100'

      - run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --maxWorkers=2

      - name: Build
        run: CI="" yarn build

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: /home/runner/work/tdex-app/tdex-app/cypress/videos/main.spec.ts.mp4
          retention-days: 5

