name: Build and push TestFlight

on:
  push:
    branches: [action]

jobs:
  testflight:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install

      - name: Set Appstore Connect User
        run: |
          bundle exec fastlane fastlane-credentials add --username=marco@sevenlabs.io --password=${{ secrets.APPSTORE_PASSWORD }}

      # Build Ionic App
      - name: install node dependencies
        run: yarn install --frozen-lockfile

      - name: build ionic ios
        run: yarn build:ios

      - name: Fastlane Beta CI
        run: bundle exec fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSPHRASE }}
          FASTLANE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
