name: Build and push TestFlight

on:
  push:
    branches: [action]

jobs:
  beta:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: action

      - name: Bundle Install
        run: bundle install

      # Build Ionic App
      - name: install node dependencies
        run: yarn install --frozen-lockfile

      - name: build ionic ios
        run: yarn build:ios

      - name: Fastlane Beta CI
        run: bundle exec fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSPHRASE }}
          FASTLANE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
