name: Build and push TestFlight

on:
  push:
    tags:
      - "v*"
jobs:
  beta:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install

      # Build Ionic App
      - name: install node dependencies
        run: yarn install --frozen-lockfile

      - name: build ionic ios
        run: yarn build:ios

      - name: Fastlane Beta CI
        run: bundle exec fastlane ios beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSPHRASE }}
          FASTLANE_USER: marco@sevenlabs.io
          FASTLANE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
