on:
  workflow_dispatch:

name: Testing

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 17
          cache: gradle

      # Build Ionic App
      - run: yarn install --frozen-lockfile

      - name: build ionic android
        run: yarn build:android
        env:
          CI: false

      # Build Android APK with Gradle
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # get current  tag
      - name: tag
        id: next_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      # get version number without the "v" for package.json increment
      - name: version
        id: next_version
        run: |
          tag=${{ steps.next_tag.outputs.tag }}
          echo ::set-output name=version::${tag:1}

      - name: Increment package.json version
        run: |
          jq '.version = "${{ steps.next_version.outputs.version }}"' package.json  > package.tmp.json
          mv package.tmp.json package.json

      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: ./android/app/build/outputs/apk/

      # Commit manifest and package.json to master
      - name: Commit & Push
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add .
          git commit -m "${{ steps.next_tag.outputs.tag }}"
          git push origin HEAD:master
